language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt
env:
  - RUST_LOG=trace
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo run --example gallery
  - cargo run --example inspect
  - cargo run --example walk
  - cargo fmt -- --check
  - cargo install --path spq-reflect
  - spq-reflect --in-path assets/gallery.frag.spv
  - spq-reflect --in-path assets/spirv-spec.frag.spv
cache: cargo
git:
  depth: 3
