name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        workspaces: |
          spq-as
          spq-core
          spq-dis
          spq-spvasm

    - name: Cargo Format
      id: cargo_format
      run: |
        cargo fmt -- --check

    - name: Cargo Build
      id: cargo_build
      run: |
        cargo build --verbose

    - name: Cargo Test
      id: cargo_test
      run: |
        cargo test --verbose

    - name: Assemble Disassemble Roundtrip
      id: cargo_build_and_test
      run: |
        cargo run -p spq-as assets/gallery.frag.spvasm -o assets/gallery.frag.spv
        cargo run -p spq-dis assets/gallery.frag.spv -o assets/gallery.frag.spvasm --no-indent
        echo git diff --exit-code --binary
